package postos.de.combustiveis;

import java.util.ArrayList;

/**
 *
 * @author GoingS
 */
public class PostosDeCombustiveisGUI extends javax.swing.JFrame {

    /**
     * Creates new form PostosDeCombustiveisGUI
     * @param listaPostos
     */
    
    private ArrayList<Posto> listaPostos;
    
    public PostosDeCombustiveisGUI(ArrayList<Posto> listaPostosNova) {
        initComponents();
        this.listaPostos = listaPostosNova;
        
        for (Posto listaPosto : listaPostosNova) {
            postosBox.addItem(listaPosto);
        }
        this.setTitle("Postos de Combustíveis");
    }

    private PostosDeCombustiveisGUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        postosBox = new javax.swing.JComboBox();
        postoLabel = new javax.swing.JLabel();
        cnpjField = new javax.swing.JTextField();
        razaoSocialField = new javax.swing.JTextField();
        bandeiraField = new javax.swing.JTextField();
        enderecoField = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        cepField = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Nome:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        postosBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                postosBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        postoLabel.setText("Posto:");

        cnpjField.setEditable(false);
        cnpjField.setText("CNPJ");

        razaoSocialField.setEditable(false);
        razaoSocialField.setText("Razão");

        bandeiraField.setEditable(false);
        bandeiraField.setText("Bandeira");

        enderecoField.setEditable(false);
        enderecoField.setText("Endereço");

        bairroField.setEditable(false);
        bairroField.setText("Bairro");

        cepField.setEditable(false);
        cepField.setText("CEP");

        botaoSalvar.setText("Salvar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        nomeField.setEditable(false);
        nomeField.setText("Nome");

        jLabel1.setText("Nome:");

        jLabel2.setText("CNPJ:");

        jLabel3.setText("Razão:");

        jLabel4.setText("Bandeira:");

        jLabel6.setText("Endereço:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Cep:");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(postoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nomeField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cnpjField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(razaoSocialField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bandeiraField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enderecoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(bairroField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(postosBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(438, 438, 438))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postoLabel)
                    .addComponent(postosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razaoSocialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandeiraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void caixasTextoAtivadas(boolean ativada){
        nomeField.setEditable(ativada);
        cnpjField.setEditable(ativada);
        razaoSocialField.setEditable(ativada);
        bandeiraField.setEditable(ativada);
        enderecoField.setEditable(ativada);
        bairroField.setEditable(ativada);
        cepField.setEditable(ativada);
    }
    
    private void limparCaixasTexto(){
        nomeField.setText("");
        cnpjField.setText("");
        razaoSocialField.setText("");
        bandeiraField.setText("");
        enderecoField.setText("");
        bairroField.setText("");
        cepField.setText("");
    }
            
    private void postosBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_postosBoxPopupMenuWillBecomeInvisible
        
        //Posto postoSelecionado = (Posto) postosBox.getItemAt(postosBox.getSelectedIndex()); // FIX
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        ///*
        nomeField.setText(postoSelecionado.toString());
        cnpjField.setText(postoSelecionado.getCnpj());
        razaoSocialField.setText(postoSelecionado.getRazaoSocial());
        bandeiraField.setText(postoSelecionado.getBandeira());
        enderecoField.setText(postoSelecionado.getEndereco());
        bairroField.setText(postoSelecionado.getBairro());
        cepField.setText(postoSelecionado.getCep());
        //*/
    }//GEN-LAST:event_postosBoxPopupMenuWillBecomeInvisible

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        this.caixasTextoAtivadas(true);
        this.limparCaixasTexto();
        
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        botaoSalvar.setEnabled(true);
        postosBox.setEnabled(false);
        this.caixasTextoAtivadas(true);
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        
        postoSelecionado.setNome(nomeField.getText());
        postoSelecionado.setCnpj(cnpjField.getText());
        postoSelecionado.setRazaoSocial(razaoSocialField.getText());
        postoSelecionado.setBandeira(bandeiraField.getText());
        postoSelecionado.setEndereco(enderecoField.getText());
        postoSelecionado.setBairro(bairroField.getText());
        postoSelecionado.setCep(cepField.getText());
        
        this.caixasTextoAtivadas(false);
        botaoSalvar.setEnabled(false);
        postosBox.setEnabled(true);
        
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        this.listaPostos.remove(postoSelecionado);
    }//GEN-LAST:event_botaoRemoverActionPerformed

    /**
     * @param args
     */
    public static void main(String[] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ArrayList<Posto> listaPostos = new ArrayList<>();
        
        Combustivel c1 = new Combustivel("Etanol", new Data(20,11,2015), 2.12f);
        Combustivel c2 = new Combustivel("Diesel", new Data(20,11,2015), 3.12f);
        Combustivel c3 = new Combustivel("Gasolina", new Data(20,11,2015), 3.59f);
        
        Posto p1 = new Posto();
        p1.setBairro("Centro");
        p1.setBandeira("BR");
        p1.setCep("97010040");
        p1.setCnpj("12345678/0001-02");
        p1.setEndereco("Rua dos Andradas, 1235");
        p1.setNome("Meu Posto");
        p1.setRazaoSocial("Razao");
        
        System.out.println(p1.toString());
        
        Posto p2 = new Posto();
        p2.setBairro("ASDSAD");
        p2.setBandeira("BR");
        p2.setCep("SD");
        p2.setCnpj("gGGGG/fefe-02");
        p2.setEndereco("Rua dos Andradas, 448949");
        p2.setNome("Postão");
        p2.setRazaoSocial("grgr");
        
        //c1.showCombustivel();
        p1.addCombustivel(c1);
        p1.addCombustivel(c2);
        p1.addCombustivel(c3);
        p1.rmvCombustivel("Etanol");
        
        listaPostos.add(p1);
        listaPostos.add(p2);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PostosDeCombustiveisGUI(listaPostos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroField;
    private javax.swing.JTextField bandeiraField;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField cepField;
    private javax.swing.JTextField cnpjField;
    private javax.swing.JTextField enderecoField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel postoLabel;
    private javax.swing.JComboBox postosBox;
    private javax.swing.JTextField razaoSocialField;
    // End of variables declaration//GEN-END:variables
}
