package postos.de.combustiveisGUI;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import postos.de.combustiveis.Combustivel;
import postos.de.combustiveis.Data;
import postos.de.combustiveis.Historico;
import postos.de.combustiveis.Posto;

/**
 *
 * @author GoingS
 */

public class PostosDeCombustiveisGUI extends javax.swing.JFrame {

    /**
     * Creates new form PostosDeCombustiveisGUI
     * @param listaPostos
     */
    
    private ArrayList<Posto> listaPostos;
    
    
    public PostosDeCombustiveisGUI(ArrayList<Posto> listaPostosNova) {
        initComponents();
        this.setTitle("Postos de Combustíveis");
        this.setResizable(true);
        this.listaPostos = listaPostosNova;
        this.atualizarBox();
        this.atualizarListaCombustiveis();
        this.preencherCaixasTexto();
    }

    private PostosDeCombustiveisGUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        postosBox = new javax.swing.JComboBox();
        postoLabel = new javax.swing.JLabel();
        cnpjField = new javax.swing.JTextField();
        razaoSocialField = new javax.swing.JTextField();
        bandeiraField = new javax.swing.JTextField();
        enderecoField = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        cepField = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        dataCombustivelField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCombustiveisList = new javax.swing.JList();
        nomeField1 = new javax.swing.JTextField();
        tipoCombustivelField1 = new javax.swing.JTextField();
        precoCombustivelField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botaoAdicionarCombustivel = new javax.swing.JButton();
        botaoRemoverCombustivel = new javax.swing.JButton();
        botaoEditarCombustivel = new javax.swing.JButton();
        botaoSalvarCombustivel = new javax.swing.JButton();
        botaoPesquisarPostos = new javax.swing.JButton();
        labelImagem = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaHistoricoPrecos = new javax.swing.JList();
        botaoProcurarImagem = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Nome:");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        postosBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                postosBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        postoLabel.setText("Posto:");

        cnpjField.setEditable(false);

        razaoSocialField.setEditable(false);

        bandeiraField.setEditable(false);

        enderecoField.setEditable(false);

        bairroField.setEditable(false);

        cepField.setEditable(false);

        botaoSalvar.setText("Salvar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        dataCombustivelField.setEditable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("CNPJ:");

        jLabel3.setText("Razão:");

        jLabel4.setText("Bandeira:");

        jLabel6.setText("Endereço:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Cep:");
        jLabel8.setToolTipText("");

        listaCombustiveisList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCombustiveisListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCombustiveisList);

        nomeField1.setEditable(false);

        tipoCombustivelField1.setEditable(false);

        precoCombustivelField.setEditable(false);

        jLabel9.setText("Tipo:");

        jLabel10.setText("Data:");

        jLabel11.setText("Preço:");

        jLabel12.setText("Combustíveis:");

        botaoAdicionarCombustivel.setText("Add");
        botaoAdicionarCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarCombustivelActionPerformed(evt);
            }
        });

        botaoRemoverCombustivel.setText("Remover");
        botaoRemoverCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverCombustivelActionPerformed(evt);
            }
        });

        botaoEditarCombustivel.setText("Editar");
        botaoEditarCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCombustivelActionPerformed(evt);
            }
        });

        botaoSalvarCombustivel.setText("Salvar");
        botaoSalvarCombustivel.setEnabled(false);
        botaoSalvarCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarCombustivelActionPerformed(evt);
            }
        });

        botaoPesquisarPostos.setText("Pesquisar postos por bairro");
        botaoPesquisarPostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarPostosActionPerformed(evt);
            }
        });

        jLabel14.setText("Histórico de preços:");

        jScrollPane2.setViewportView(listaHistoricoPrecos);

        botaoProcurarImagem.setText("Procurar imagem");
        botaoProcurarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarImagemActionPerformed(evt);
            }
        });

        jLabel13.setText("Imagem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(postoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(postosBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(razaoSocialField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bandeiraField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(botaoProcurarImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(precoCombustivelField)
                        .addComponent(dataCombustivelField)
                        .addComponent(tipoCombustivelField1)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botaoPesquisarPostos, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAdicionarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemoverCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(postoLabel)
                                    .addComponent(postosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(nomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cnpjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(razaoSocialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bandeiraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoCombustivelField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataCombustivelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoCombustivelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoProcurarImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoAdicionarCombustivel)
                            .addComponent(botaoRemoverCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSalvarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoEditarCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoPesquisarPostos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixasTextoPostoAtivadas(boolean ativada){
        nomeField1.setEditable(ativada);
        cnpjField.setEditable(ativada);
        razaoSocialField.setEditable(ativada);
        bandeiraField.setEditable(ativada);
        enderecoField.setEditable(ativada);
        bairroField.setEditable(ativada);
        cepField.setEditable(ativada);
    }
    
    private void caixasTextoCombustivelAtivadas(boolean ativada){
        tipoCombustivelField1.setEditable(ativada);
        dataCombustivelField.setEditable(ativada);
        precoCombustivelField.setEditable(ativada);
    }
    
    private void limparTodasCaixasTexto(){
        nomeField1.setText("");
        cnpjField.setText("");
        razaoSocialField.setText("");
        bandeiraField.setText("");
        enderecoField.setText("");
        bairroField.setText("");
        cepField.setText("");
        labelImagem.setIcon(null);
        
        tipoCombustivelField1.setText("");
        dataCombustivelField.setText("");
        precoCombustivelField.setText("");
        
        listaCombustiveisList.removeAll();
        this.atualizarListaCombustiveis();
    }
    
    private void preencherCaixasTexto(){
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        if(postoSelecionado != null){
            nomeField1.setText(postoSelecionado.toString());
            cnpjField.setText(postoSelecionado.getCnpj());
            razaoSocialField.setText(postoSelecionado.getRazaoSocial());
            bandeiraField.setText(postoSelecionado.getBandeira());
            enderecoField.setText(postoSelecionado.getEndereco());
            bairroField.setText(postoSelecionado.getBairro());
            cepField.setText(postoSelecionado.getCep());
            //labelImagem.setIcon(redimensionar(localArquivo));
            labelImagem.setIcon(redimensionar(postoSelecionado.getImagem()));
        }
        else 
            this.limparTodasCaixasTexto();
    }
    
    private void atualizarBox(){
        postosBox.removeAllItems();
        for (Posto listaPosto : listaPostos) 
            postosBox.addItem(listaPosto);
    }
    
    private void atualizarListaCombustiveis(){
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        DefaultListModel model1 = new DefaultListModel();
        
        if(postoSelecionado != null)
            for(Combustivel combustivel : postoSelecionado.getCombustiveis())
                model1.addElement(combustivel);
        
        
        listaCombustiveisList.setModel(model1);
        this.atualizarCaixasCombustiveis();
        this.atualizarListaHistorico();
    }
    
    private void atualizarListaHistorico(){
        Combustivel combustivelSelecionado = (Combustivel) listaCombustiveisList.getSelectedValue();
        DefaultListModel model1 = new DefaultListModel();
        
        if(combustivelSelecionado != null)
            for(Historico historico : combustivelSelecionado.getHistorico())
                model1.addElement(historico);
        
        listaHistoricoPrecos.setModel(model1);
        
    }
    
    private void atualizarCaixasCombustiveis(){
        Combustivel combustivelSelecionado = (Combustivel) listaCombustiveisList.getSelectedValue();
        if(combustivelSelecionado != null){
            tipoCombustivelField1.setText(combustivelSelecionado.getTipo());
            dataCombustivelField.setText(combustivelSelecionado.getData().toString());
            precoCombustivelField.setText(combustivelSelecionado.getPreco() + "");
        }
        else{
            tipoCombustivelField1.setText("");
            dataCombustivelField.setText("");
            precoCombustivelField.setText("");
        }  
    }
    
    private ImageIcon redimensionar(String imagemAntigaString){
        ImageIcon icone = new ImageIcon(imagemAntigaString);
            
        Image imagem = icone.getImage();
        Image novaImagem = imagem.getScaledInstance(241, 169, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(novaImagem);
    }
    
    private void postosBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_postosBoxPopupMenuWillBecomeInvisible
        this.preencherCaixasTexto();
        this.atualizarListaCombustiveis();
    }//GEN-LAST:event_postosBoxPopupMenuWillBecomeInvisible

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        this.limparTodasCaixasTexto();
        this.caixasTextoPostoAtivadas(true);
        postosBox.setEnabled(false);
        botaoSalvar.setEnabled(true);
            
        Posto novoPosto = new Posto();
        listaPostos.add(novoPosto);
        this.atualizarBox();
        postosBox.setSelectedItem(novoPosto);
        this.atualizarListaCombustiveis();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        if(!listaPostos.isEmpty()){
            botaoSalvar.setEnabled(true);
            postosBox.setEnabled(false);
            caixasTextoPostoAtivadas(true);
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        
        postoSelecionado.setNome(nomeField1.getText());
        postoSelecionado.setCnpj(cnpjField.getText());
        postoSelecionado.setRazaoSocial(razaoSocialField.getText());
        postoSelecionado.setBandeira(bandeiraField.getText());
        postoSelecionado.setEndereco(enderecoField.getText());
        postoSelecionado.setBairro(bairroField.getText());
        postoSelecionado.setCep(cepField.getText());
        
        
        this.caixasTextoPostoAtivadas(false);
        botaoSalvar.setEnabled(false);
        postosBox.setEnabled(true);
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        this.listaPostos.remove(postoSelecionado);
        this.atualizarBox();
        
        if(this.listaPostos.size() > 0){
            this.atualizarBox();
            postosBox.setSelectedIndex(0);
        }
        else
            postosBox.setSelectedItem(null);
        
        
        this.preencherCaixasTexto();
        this.atualizarListaCombustiveis();
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void listaCombustiveisListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCombustiveisListMouseClicked
        Combustivel combustivelSelecionado = (Combustivel) listaCombustiveisList.getSelectedValue();
        if(combustivelSelecionado != null){
            tipoCombustivelField1.setText(combustivelSelecionado.getTipo());
            dataCombustivelField.setText(combustivelSelecionado.getData().toString());
            precoCombustivelField.setText(combustivelSelecionado.getPreco() + "");
            this.atualizarListaHistorico();
        }
    }//GEN-LAST:event_listaCombustiveisListMouseClicked

    private void botaoAdicionarCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarCombustivelActionPerformed
        Posto PostoSelecionado = (Posto) postosBox.getSelectedItem();
        Combustivel novoCombustivel = new Combustivel();
        
        
        PostoSelecionado.getCombustiveis().add(novoCombustivel);
        this.atualizarListaCombustiveis();
        listaCombustiveisList.setSelectedValue(novoCombustivel, false);
        
        botaoSalvarCombustivel.setEnabled(true);
        postosBox.setEnabled(false);
        this.caixasTextoCombustivelAtivadas(true);
    }//GEN-LAST:event_botaoAdicionarCombustivelActionPerformed

    private void botaoRemoverCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverCombustivelActionPerformed
        Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
        Combustivel combustivelSelecionado = (Combustivel) listaCombustiveisList.getSelectedValue();
        
        postoSelecionado.getCombustiveis().remove(combustivelSelecionado);
        this.atualizarListaCombustiveis();
    }//GEN-LAST:event_botaoRemoverCombustivelActionPerformed

    private void botaoEditarCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCombustivelActionPerformed
        botaoSalvarCombustivel.setEnabled(true);
        postosBox.setEnabled(false);
        this.caixasTextoCombustivelAtivadas(true);
        this.listaCombustiveisList.setEnabled(false);  
    }//GEN-LAST:event_botaoEditarCombustivelActionPerformed

    private void botaoSalvarCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarCombustivelActionPerformed
        Combustivel combustivelSelecionado = (Combustivel) listaCombustiveisList.getSelectedValue();
        
        if(this.precoCombustivelField.getText().isEmpty())
            this.precoCombustivelField.setText("0");
        
        combustivelSelecionado.setTipo(tipoCombustivelField1.getText());
        if(!combustivelSelecionado.getHistorico().isEmpty())
            combustivelSelecionado.alterarPrecoComHistorico(Float.parseFloat(precoCombustivelField.getText()),
                 Data.stringToData(dataCombustivelField.getText()));
        else{
            combustivelSelecionado.setPreco(Float.parseFloat(precoCombustivelField.getText()));
            combustivelSelecionado.setData(Data.stringToData(dataCombustivelField.getText()));
        }
        
        this.caixasTextoCombustivelAtivadas(false);
        this.botaoSalvarCombustivel.setEnabled(false);
        this.postosBox.setEnabled(true);
        this.listaCombustiveisList.setEnabled(true);
        this.atualizarCaixasCombustiveis();
        this.atualizarListaHistorico();
        this.listaCombustiveisList.setSelectedValue(combustivelSelecionado, true);
        
    }//GEN-LAST:event_botaoSalvarCombustivelActionPerformed

    private void botaoPesquisarPostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarPostosActionPerformed
        if(!listaPostos.isEmpty()){
            PostosPesquisadosGUI postosPesquisados = new PostosPesquisadosGUI(this.listaPostos);
            postosPesquisados.setTitle("Pesquisando postos");
            postosPesquisados.setVisible(true);
        }
    }//GEN-LAST:event_botaoPesquisarPostosActionPerformed

    private void botaoProcurarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarImagemActionPerformed
        JFileChooser fc = new JFileChooser();
        if(fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            String localArquivo = f.getAbsolutePath();
            Posto postoSelecionado = (Posto) postosBox.getSelectedItem();
            
            postoSelecionado.setImagem(localArquivo);
            labelImagem.setIcon(redimensionar(localArquivo));
        }
    }//GEN-LAST:event_botaoProcurarImagemActionPerformed

    /**
     * @param args
     */
    public static void main(String[] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostosDeCombustiveisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ArrayList<Posto> listaPostos = new ArrayList<>();
        
        Combustivel c1 = new Combustivel("Etanol", new Data(20,11,2015), 2.12f);
        Combustivel c2 = new Combustivel("Diesel", new Data(20,11,2015), 3.12f);
        Combustivel c3 = new Combustivel("Gasolina", new Data(20,11,2015), 3.59f);
        Posto p1 = new Posto();
        p1.setBairro("Centro");
        p1.setBandeira("BR");
        p1.setCep("97010040");
        p1.setCnpj("12345678/0001-02");
        p1.setEndereco("Rua dos Andradas, 1235");
        p1.setNome("Meu Posto");
        p1.setRazaoSocial("Razao");
        
        System.out.println(p1.toString());
        
        Posto p2 = new Posto();
        p2.setBairro("ASDSAD");
        p2.setBandeira("BR");
        p2.setCep("SD");
        p2.setCnpj("gGGGG/fefe-02");
        p2.setEndereco("Rua dos Andradas, 448949");
        p2.setNome("Postão");
        p2.setRazaoSocial("grgr");
        
        //c1.showCombustivel();
        p1.addCombustivel(c1);
        p1.addCombustivel(c2);
        p1.addCombustivel(c3);
        p1.rmvCombustivel("Etanol");
        
        listaPostos.add(p1);
        listaPostos.add(p2);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PostosDeCombustiveisGUI(listaPostos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroField;
    private javax.swing.JTextField bandeiraField;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAdicionarCombustivel;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoEditarCombustivel;
    private javax.swing.JButton botaoPesquisarPostos;
    private javax.swing.JButton botaoProcurarImagem;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoRemoverCombustivel;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoSalvarCombustivel;
    private javax.swing.JTextField cepField;
    private javax.swing.JTextField cnpjField;
    private javax.swing.JTextField dataCombustivelField;
    private javax.swing.JTextField enderecoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JList listaCombustiveisList;
    private javax.swing.JList listaHistoricoPrecos;
    private javax.swing.JTextField nomeField1;
    private javax.swing.JLabel postoLabel;
    private javax.swing.JComboBox postosBox;
    private javax.swing.JTextField precoCombustivelField;
    private javax.swing.JTextField razaoSocialField;
    private javax.swing.JTextField tipoCombustivelField1;
    // End of variables declaration//GEN-END:variables
}
